#!/bin/bash

hash docker 2>/dev/null || not_found=true 
if [[ $not_found ]]; then
    echo "Docker is not installed! Install docker first."
    exit 1
fi

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <path to dataset> [options]"
    exit 0
fi

if [[ $* == *--help* ]] || [[ $* == *-h* ]]; then
    docker run -ti --rm --entrypoint /app/run.py uav4geo/nodecm --help
fi

GPU_FLAGS=""
if [[ ! -z "$USE_GPU" ]]; then
    GPU_FLAGS="--gpus all"
fi

if [[ -d "$1" ]]; then
    echo docker run $GPU_FLAGS -ti --rm --entrypoint /app/run.py -v $(realpath "$1"):/datasets/project uav4geo/nodecm --project-path /datasets project "${@:2}"
else
    echo "$1 is not a directory"
fi

